### ISSUE TITLE
nrm broken on npm v8.0.0

### ISSUE THREAD

**Issue by betgar** [Pana/nrm#104]
**npm v8.0.0 remove support for require('npm').**

https://github.com/npm/cli/releases/tag/v8.0.0

`The purpose of this release is to drop support for old node versions and
to remove support for require('npm'). There are no other breaking
changes.`

**Comment by NeverSeeBefore** [comment]
+1，

**Comment by bbb324** [comment]
change package.json npm to 7.5.4, and delete node_modules, and execute npm i again, that works for me
