### ISSUE TITLE
为什么列表前面没有星号？

### ISSUE THREAD

**Issue by xiaoyu-666** [Pana/nrm#109]
![image](https://user-images.githubusercontent.com/27267958/136925953-fe1c76ff-832d-4deb-ab12-ba3c70a1ac49.png)

为什么列表前面没有星号？

**Comment by 1955825621** [comment]
巧了我也没星

**Comment by CupidTian** [comment]
可以使用nrm test命令进行测速，然后这个里面的星号应该和nrm ls使用的是一样的
