### ISSUE TITLE
nrm ls 依然不带星或nrm current 不显示当前？

### ISSUE THREAD

**Issue by fch89** [Pana/nrm#111]
在最新版，1.2.5 依然没有解决这个问题？？

从旧版本看 .nrmrc 文件中只会保存一条记录。
在1.2.5 中 cli.js 文件的 211 行， 判断逻辑是有问题的。hasOwnProperty 判断不应从 customRegistries中是否存在用户输入的name变量传递的值。[如：npm、taobao]  ，判断应该从所有allRegistries 的集合中判断是否存在输入 use 后面的值。

`
if (hasOwnProperty(allRegistries, name) && (name in registries || customRegistries[name].registry === registry.registry)) {
//if (!hasOwnProperty(customRegistries, name) && (name in registries || customRegistries[name].registry === registry.registry)) {
    registry[FIELD_IS_CURRENT] = true;
    customRegistries[name] = registry;
    
}

`

希望作者处理一下该问题！

**Comment by lpreterite** [comment]
遇到相同情况，从1.2.1版本更新至1.2.5后就没法识别当前的registry。能确认的是在版本1.2.1是正常的。

**Comment by lisongtao0704** [comment]
遇到相同情况，还有我在mac M1芯片的上面安装1.2.1也不行呀

**Comment by adams549659584** [comment]
npm上新版的代码似乎是8年前的源码，是不是发布版本出现了问题？ @i5ting

**Comment by adams549659584** [comment]
![image](https://user-images.githubusercontent.com/10492939/144024914-6550cb40-b9ac-407d-9033-93d666ab5788.png)
![image](https://user-images.githubusercontent.com/10492939/144024939-1d834690-0d6c-458e-8127-6b2330f275df.png)
这是npm下载的最新的包，但是不带星及当前的，看了下源码应该是8年前的

**Comment by adams549659584** [comment]
有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常

![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)

**Comment by shalldie** [comment]
也遇到了，希望能够早点解决，看着挺揪心了 =。=

**Comment by lpreterite** [comment]
> 有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常
> 
> ![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)

这位同学PR一下更好

**Comment by adams549659584** [comment]
> > 有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常
> > ![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)
> 
> 这位同学PR一下更好

主要是代码没问题的，只是可能打包到npm的版本出问题了，搞个合并PR时自动打包好像也不大好

**Comment by Minori-ty** [comment]
同样的问题，本来还想提个issue呢

**Comment by Minori-ty** [comment]
> > 有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常
> > ![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)
> 
> 这位同学PR一下更好

我这里依旧是不行阿。win10

**Comment by Minori-ty** [comment]
> > > 有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常
> > > ![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)
> > 
> > 
> > 这位同学PR一下更好
> 
> 我这里依旧是不行阿。win10

应该是缓存的问题，我到C:\Users\15638\AppData\Roaming\npm\node_modules 里面关于nrm的包全都删了，并且把npm_cache缓存的文件也删了。
然后就好了。
![image](https://user-images.githubusercontent.com/79521943/148374062-584f8f31-7f48-4819-b67e-6acd2b23dcce.png)

**Comment by adams549659584** [comment]
> > > > 有需要的同学可以先用这个（npm install -g @adams549659584/nrm），github action 自动发布最新到npm，使用命令一致，星号正常
> > > > ![image](https://user-images.githubusercontent.com/10492939/144181998-9df7c106-308d-4038-8e21-e3e73011d4e6.png)
> > > 
> > > 
> > > 这位同学PR一下更好
> > 
> > 
> > 我这里依旧是不行阿。win10
> 
> 应该是缓存的问题，我到C:\Users\15638\AppData\Roaming\npm\node_modules 里面关于nrm的包全都删了，并且把npm_cache缓存的文件也删了。 然后就好了。 ![image](https://user-images.githubusercontent.com/79521943/148374062-584f8f31-7f48-4819-b67e-6acd2b23dcce.png)

嗯嗯，一般卸载原来的再装下这个就好

**Comment by rawbin-** [comment]
发现现在直接安装源码是ok的
```
npm install Pana/nrm -g
```

**Comment by uwang** [comment]
这个包的发布有问题，暂时还是直接安装源码吧

**Comment by 515789588** [comment]
nrm use 原始的几个源不带*号，并且切换好像不生效，
新增的源就可以，所以想用哪个源，可以暂时把他搞个别名来用
npm ---------- https://registry.npmjs.org/
yarn --------- https://registry.yarnpkg.com/
tencent ------ https://mirrors.cloud.tencent.com/npm/
cnpm --------- https://r.cnpmjs.org/
taobao ------- https://registry.npmmirror.com/
npmMirror ---- https://skimdb.npmjs.com/registry/
31npm -------- http://package.31huiyi.com/repository/npm-group/
* cyarn -------- https://registry.yarnpkg.com/

**Comment by PinkCar** [comment]
![Snipaste](https://user-images.githubusercontent.com/37258122/157792825-567f7d57-e2a4-4fa8-b820-1d9249071d6e.png)
![output](https://user-images.githubusercontent.com/37258122/157793245-c8b5159a-7423-448b-961a-8956e9239e39.png)
Modify 211 lines of code in cli.js,The problem can be solved by changing && to | |.

**Comment by liurongqing** [comment]
暂时 github 仓库直接安装

```bash
npm i -g git+https://github.com/Pana/nrm.git
```
![31650209933_ pic](https://user-images.githubusercontent.com/26001948/163721724-9c2a0673-ce64-4125-a3d8-433eda9f3d44.jpg)

**Comment by cll123456** [comment]
@liurongqing  非常感谢，这种方式是ok的

**Comment by codepandy** [comment]
上面说的直接源安装失败，@liurongqing说的亲测有效

**Comment by yuxixi0613** [comment]
> ![Snipaste](https://user-images.githubusercontent.com/37258122/157792825-567f7d57-e2a4-4fa8-b820-1d9249071d6e.png) ![output](https://user-images.githubusercontent.com/37258122/157793245-c8b5159a-7423-448b-961a-8956e9239e39.png) Modify 211 lines of code in cli.js,The problem can be solved by changing && to | |.

Good Job！！！

**Comment by weijuer** [comment]
Good Job！！！
