### ISSUE TITLE
PR:add engines prompt node version in package.json

### ISSUE THREAD

**Issue by chen00jian** [Pana/nrm#122]
## Feature request

**What is the expected behavior?**
I want to know the supported versions of NRM when installing NRM in different node versions

**What is motivation or use case for adding/changing the behavior?**
It can quickly locate the problem and find the NRM matching the appropriate node

**node:v8.17.0 install nrm 

An error is reported during installation. I need to know the NRM supported by my current node**

<img width="730" alt="x1" src="https://user-images.githubusercontent.com/3582728/147531608-fee9f397-501a-4b59-8816-d6b9ef2df4f6.png">

The node version supported by the current project will be prompted in projects such as vite / webpack

vite:
<img width="478" alt="vite" src="https://user-images.githubusercontent.com/3582728/147531733-74139939-c8a4-47f3-a6f9-ba04a223a51e.png">
webpack:
<img width="520" alt="webpack" src="https://user-images.githubusercontent.com/3582728/147531746-12a317db-6ca5-4f65-9ad7-29ff4911aaf7.png">

**How should this be implemented in your opinion?**

in package.json add engines configuration information！
eg:

` "engines": {
    "node": ">=12.2.0"
  },`

**Comment by chen00jian** [comment]
reference [https://github.com/kelektiv/node.bcrypt.js](url)

<h2 style="box-sizing: border-box; color: rgb(17, 17, 17); margin: 8px 0px 16px; padding-bottom: 8px; font-weight: 600; line-height: 1.25; font-size: 1.875rem; border-bottom: 1px solid rgba(0, 0, 0, 0.1); letter-spacing: -0.3px; font-family: &quot;Source Sans Pro&quot;, &quot;Lucida Grande&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Version Compatibility</h2>

Node Version | Bcrypt Version
-- | --
0.4 | <= 0.4
0.6, 0.8, 0.10 | >= 0.5
0.11 | >= 0.8
4 | <= 2.1.0
8 | >= 1.0.3 < 4.0.0
10, 11 | >= 3
12 onwards | >= 3.0.6

**Comment by i5ting** [comment]
before pr，we need add ci for node version

**Comment by chouchouji** [comment]
I had added `engines` into `package.json`. The related pr is #191. Can you close this issue? Thanks. @iosh
