### ISSUE TITLE
请求超时，抛出错误

### ISSUE THREAD

**Issue by Minori-ty** [Pana/nrm#123]
今天跑了一下nrm test，突然间抛出了一个错误。我以为是出bug了，没想到是请求超时。

不过我觉得这样设置不太合理，会让人看上去以为程序出bug了。请求超时的话，希望能够让某个对应的源显示超时就行了。
![image](https://user-images.githubusercontent.com/79521943/148406044-09cb822e-7fd5-42e6-ba35-015913cadd56.png)

**Comment by i5ting** [comment]
https://github.com/Pana/nrm/pull/124
