### ISSUE TITLE
为什么使用 nrm ls 不显示星号了?

### ISSUE THREAD

**Issue by BaiGuangTeng** [Pana/nrm#126]

**Comment by rawbin-** [comment]
同样的问题

**Comment by rawbin-** [comment]
发现现在直接安装源码是ok的
```
npm install Pana/nrm -g
```

**Comment by BaiGuangTeng** [comment]
> 发现现在直接安装源码是ok的
> 
> ```
> npm install Pana/nrm -g
> ```

是的, 通过 npm install Pana/nrm -g 就好了, thank u

**Comment by amandafanny** [comment]
![image](https://user-images.githubusercontent.com/54808661/150315910-cd7ade71-969d-4106-8b97-b3df92bd06aa.png)
