### ISSUE TITLE
1.2.5 released on npm, using nrm ls commands, no normal display, current source tag

### ISSUE THREAD

**Issue by beezen** [Pana/nrm#129]
The 1.2.5 version released on NPM is inconsistent with the 1.2.5 version of the Master branch on Github. It is omissions when the 1.2.5 version is released.When using the 1.2.5 version released on NPM, use NRM LS unable to display the current source tag, there is a problem logic here, as shown:
![image](https://user-images.githubusercontent.com/13111739/154011810-2888f1c9-f881-4b60-816c-1a9503145845.png)

**Comment by VectorLu** [comment]
And `npm current` has no response
![image](https://user-images.githubusercontent.com/12776182/154193535-91d515b8-4307-42ce-ab5d-04120345c929.png)

**Comment by PinkCar** [comment]
![Snipaste](https://user-images.githubusercontent.com/37258122/157792013-5b9e0672-de21-4196-8272-b367914125e7.png)
Modify 211 lines of code in cli.js,Changing && to | | can solve your problem.
