### ISSUE TITLE
nrm ls * hidden

### ISSUE THREAD

**Issue by soyof** [Pana/nrm#130]
cli.js

```function onList () {
    getCurrentRegistry(function (cur) {
        var info = [''];
        var allRegistries = getAllRegistry();
        const keys = Object.keys(allRegistries);
        const len = Math.max(...keys.map(key => key.length)) + 3;
		

        Object.keys(allRegistries).forEach(function (key) {
            var item = allRegistries[key];
            //  bug    item[FIELD_IS_CURRENT]  ---> undefined
            var prefix = item[FIELD_IS_CURRENT] && equalsIgnoreCase(item.registry, cur) ? '* ' : '  ';   //  '   '

            info.push(prefix + key + line(key, len) + item.registry);
        });

        info.push('');
        printMsg(info);
    });
}

**Comment by 868618** [comment]
me too

**Comment by codepandy** [comment]
the same question.

**Comment by zhenya-zhu** [comment]
Same issue. Use `npm config ls` could see that registry switched successfully, but nrm does not show the `*`

M1 Mac, Zsh

<img width="881" alt="image" src="https://user-images.githubusercontent.com/3053802/199450314-531bf396-8a4d-4e2b-b8f2-6f0024f9e86e.png">

**Comment by win-96** [comment]
nrm的 cli.js 的141行 &&换成||就好了

**Comment by Dennis-Dong** [comment]
The same question. However, nrm test can be used to show that

**Comment by Dennis-Dong** [comment]
> 

![image](https://user-images.githubusercontent.com/75057705/205225316-0edfab4d-c4ed-4cc5-ab85-17be5fc6a814.png)

**Comment by soyof** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
