### ISSUE TITLE
node version v16.18.0  ERROR: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by BigHugeC4** [Pana/nrm#147]
const open = require('open');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\npm\node_modules\nrm\node_modules\open\index.js from D:\npm\node_modules\nrm\cli.js not supported.
Instead change the require of index.js in D:\npm\node_modules\nrm\cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\npm\node_modules\nrm\cli.js:9:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by BigHugeC4** [comment]
"open" use version 8.4.2 is fine

**Comment by 276378532** [comment]
遇到了同样的问题  插眼

**Comment by wanglin447563345** [comment]
遇到了同样的问题 插眼

**Comment by LuoRiWuSheng** [comment]
从本地

```
npm i nrm -g
```
2023-03-21 9：23 分最新版本
下载的版本是 1.2.5
依赖的 open包 是 
![image](https://user-images.githubusercontent.com/23192097/226498563-a8866114-311b-45d9-9449-4933990d4d90.png)

nrm 下的 node_modules 里面下载的是 open的最新版本 

![image](https://user-images.githubusercontent.com/23192097/226498654-fb206e6f-c0ab-4872-93e0-c82647223d79.png)

应该使用 open 的   CommonJs规范的包
现在 open: :9.0.0  是  ES Module 版本的

目前只能降级 nrm 为  

这在  open 的github 上也是看到了 更新日志  https://github.com/sindresorhus/open/releases

![image](https://user-images.githubusercontent.com/23192097/226498830-12902079-9d40-428f-b3fa-f59147914bcf.png)

**Comment by ltchou** [comment]
try to use this command to lock the version of open pacakge at 8.4.2
`npm install -g nrm open@8.4.2 --save`

**Comment by RikaShiro** [comment]
got the same error message

**Comment by Diluka** [comment]
just install it from GitHub directly
```bash
npm i -g github:Pana/nrm
```

**Comment by cuihuale2021** [comment]
> try to use this command to lock the version of open pacakge at 8.4.2 `npm install -g nrm open@8.4.2 --save`

解决问题了，感谢！

**Comment by LuoRiWuSheng** [comment]
> 


Installing from github does not seem to be a good solution to network congestion, and there may be download failures

**Comment by LuoRiWuSheng** [comment]
> just install it from GitHub directly
> 
> ```shell
> npm i -g github:Pana/nrm
> ```

Installing from github does not seem to be a good solution to network congestion, and there may be download failures

**Comment by LuoRiWuSheng** [comment]
> try to use this command to lock the version of open pacakge at 8.4.2 `npm install -g nrm open@8.4.2 --save`
这不是nrm包的内部依赖吗，为何要单独全局安装，似乎不是很好的解决方案

像我们在 jekenis 自动发布， 以前只要   全局安装 npm - nrm -g 即可； 现在多了一个前置包  open, 对 运维也是一个负担

毕竟真的有运维搞不懂 node 和前端这个庞大的生态

**Comment by xiao994** [comment]
插眼

**Comment by xllily** [comment]
> try to use this command to lock the version of open pacakge at 8.4.2 `npm install -g nrm open@8.4.2 --save`

If unresolved, also consider checking [#156](https://github.com/Pana/nrm/issues/156#issuecomment-1558448955) as an additional option.
