### ISSUE TITLE
在nvm中初次的安装中可以，切换node版本安装就不行了

### ISSUE THREAD

**Issue by hqzh** [Pana/nrm#150]
![微信截图_20230323104246](https://user-images.githubusercontent.com/26128706/227087065-414a6665-ab5c-48c4-ad52-96f5f5f72af2.png)

**Comment by LuoRiWuSheng** [comment]
首先， 这个报错和 nvm 切换node包版本无关
1、你在 node  14.21.3 版本的时候， 之前，已经将 nrm 全局安装， 文件已经在本地
2、在你切换 node 版本的时候，  13.14.0  目录的node_modules 里面并没有 nrm ， 所以，你又重新 npm i nrm -g 全局安装， 此时是安装了最新的 nrm 但是，最新的nrm 依赖的open 包最近更新了版本，open包的语法改为了 ESM 格式， 但是 nrm 引用还是 require, 导致语法不兼容， 所以报错

最简单的解决办法是  `npm i nrm@1.0.0 -g`     锁包

相关报错，我在另外一个 链接有做出说明   

修复的 pr    https://github.com/Pana/nrm/pull/148
详细说明： https://github.com/Pana/nrm/issues/147

**Comment by hqzh** [comment]
> 首先， 这个报错和 nvm 切换node包版本无关 1、你在 node 14.21.3 版本的时候， 之前，已经将 nrm 全局安装， 文件已经在本地 2、在你切换 node 版本的时候， 13.14.0 目录的node_modules 里面并没有 nrm ， 所以，你又重新 npm i nrm -g 全局安装， 此时是安装了最新的 nrm 但是，最新的nrm 依赖的open 包最近更新了版本，open包的语法改为了 ESM 格式， 但是 nrm 引用还是 require, 导致语法不兼容， 所以报错
> 
> 最简单的解决办法是 `npm i nrm@1.0.0 -g` 锁包
> 
> 相关报错，我在另外一个 链接有做出说明
> 
> 修复的 pr #148 详细说明： #147

棒，生效！
