### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by long-woo** [Pana/nrm#152]
Cannot be used in node 18.

node: 18.15.0
npm: 9.5.0

<img width="565" alt="image" src="https://user-images.githubusercontent.com/3394035/228558408-d2c52848-1549-4c13-a353-c9cebf4f14a1.png">

**Comment by mzl980425** [comment]
+1

**Comment by maxiaoqu** [comment]
i use myself package with inrm，you can run bash as “npm install invm -g”，details view in: https://github.com/maxiaoqu/nrm
