### ISSUE TITLE
require() of ES modules is not supported.

### ISSUE THREAD

**Issue by senfish** [Pana/nrm#153]
**nrm**: 1.2.5

<img width="823" alt="image" src="https://user-images.githubusercontent.com/49187663/229347493-3394999e-bbe8-4954-a940-1a7b948934d6.png">

我很好奇，我进入了这个`chalk`地址查看一下这个包`package.json`，居然是`5.2.0`，为什么会安装最新的`ES Module`呢，按道理应该是V4版本的`chalk`。

**Comment by endwalker** [comment]
npm install nrm open@8.4.2 -g

**Comment by wjq990112** [comment]
open 这个包从 9.x 开始改成了 Native ESM，不再支持 require 的方式引入，nrm 应该锁定一下依赖到这个版本

**Comment by marswong** [comment]
@i5ting the version `1.2.5` published to npm is different from the source code of the `master` branch.

**Comment by kiinlam** [comment]
试了下这个，也可以：
```
npm install -g Pana/nrm
```

**Comment by deepraining** [comment]
直接从github仓库安装：`cnpm i -g nrm@git@github.com:Pana/nrm.git`

**Comment by 285878535** [comment]
use this command: `npm install -g nrm open@8.4.2 --save`

**Comment by CaptainOfPhB** [comment]
Try `nrm i -g nrm-ng`.
