### ISSUE TITLE
关于报错的问题throw new ERR_REQUIRE_ESM、const open = require('open')、node 升级到18.xx.xx后包错的问题解决

### ISSUE THREAD

**Issue by maxiaoqu** [Pana/nrm#157]
1、升级nrm里面open模块
npm install -g nrm open@8.4.2 --save

2、使用替代品
【替代品1 (我基于它进行了改造)】npm install invm -g  （详情地址：https://github.com/maxiaoqu/nrm ）
【替代品2】npm i nrm-sunny1011111 -g  （详情地址：https://www.npmjs.com/package/nrm-sunny1011111 ）

**Comment by Roger-jc-Lu** [comment]
The solution solved my problem for now, thank you.

**Comment by wsgouwan** [comment]
me too , thank you

**Comment by fireMan-34** [comment]
I have same problem, thank you.

**Comment by Alexzzzzzz1** [comment]
goooood

**Comment by zerobin** [comment]
goooood

**Comment by yiki17** [comment]
me three, thank you

**Comment by weidesh** [comment]
嗯嗯，我也遇到了这个问题，我nrm目录下运行npm install open@8.4.2 --save，没有全局安装open，谢谢您的无私分享 @maxiaoqu

**Comment by fyzhu** [comment]
`npm i @fyzhu/nrm -g`

**Comment by CaptainOfPhB** [comment]
[`npm i -g nrm-ng`](https://www.npmjs.com/package/nrm-ng)
