### ISSUE TITLE
nodejs 20上面無法使用

### ISSUE THREAD

**Issue by zzzgit** [Pana/nrm#158]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/1060733/235975862-edf9136b-93b3-4a93-b55b-683c55d7227c.png">

**Comment by telescope114** [comment]
你试试看 `npm i -g open@8` 后能不能使用

**Comment by brandonxiang** [comment]
为啥这个问题并不能直接有nrm解决？

**Comment by fritx** [comment]
> 你试试看 `npm i -g open@8` 后能不能使用

这种esm问题真的挺烦，用户总是被上游和生态“一刀切”太烦了
我这边还需要删掉`nrm/node_modules/open`才可以，以下命令仅供参考：

```sh
npm i -g open@8
rm -rf $(dirname $(which node))/../lib/node_modules/nrm/node_modules/open
nrm ls
```

**Comment by fyzhu** [comment]
`npm i @fyzhu/nrm -g`

**Comment by i5ting** [comment]
已fix，使用v1.2.6
