### ISSUE TITLE
Could not get normal auth or publish progress

### ISSUE THREAD

**Issue by yorkie** [Pana/nrm#16]
Hey Wang, the `nrm` is really doing a fucking awesome work on fetching packages together with others, but it still has a little bit issue on those commands which should connect with the "npm.registry.com" like `npm adduser`.

I just tracked the error log and found:

```
http request GET http://r.cnpmjs.org/-/user/org.couchdb.user:yorkie?write=true
```

Yea, if nrm could temporarily proxy the "r.cnpmjs.org" to "registry.npmjs.org", that would be such a neat work. **BTW**, I resolved this problem just tweaks the endpoint.

**Comment by yorkie** [comment]
Ping @Pana

**Comment by Pana** [comment]
Yeah it definitely is a problem, What do you mean by tweaks the endpoint ?

**Comment by yorkie** [comment]
I mean use the original registry: npm, namely I think nrm should only proxy the **read** requests.

**Comment by Pana** [comment]
For now nrm just change the registry what npm use, so if you want publish module you must switch back to npm officail registry
