### ISSUE TITLE
这个项目当前还能发布新版吗？

### ISSUE THREAD

**Issue by manooog** [Pana/nrm#161]
我遇到了大多数人遇到的有关版本依赖的问题，即：

**当前版本的nrm无法支持最新的open@9模块，因此需要锁死open的版本到v8**

但是这个问题只需要基于现在master 分支的代码直接发布一个新版即可解决。我看到 @i5ting 狼叔有merge 代码的权限，那有人可以更新一下对应npm包的版本吗？🙏

**Comment by i5ting** [comment]
提一个pr给我吧，我看看测试里还有好多问题

**Comment by i5ting** [comment]
> 我遇到了大多数人遇到的有关版本依赖的问题，即：
> 
> **当前版本的nrm无法支持最新的open@9模块，因此需要锁死open的版本到v8**
> 
> 但是这个问题只需要基于现在master 分支的代码直接发布一个新版即可解决。我看到 @i5ting 狼叔有merge 代码的权限，那有人可以更新一下对应npm包的版本吗？🙏

已发布v1.2.6
