### ISSUE TITLE
nrm del does not seem to work

### ISSUE THREAD

**Issue by rootical** [Pana/nrm#17]
Hello, thanks for your work.

I can not delete any registry:

`nrm del test`
`nrm ls`
And I still see the test registry.

**Comment by shallwefootball** [comment]
+

**Comment by lococo--0** [comment]
+

**Comment by GoldyMark** [comment]
Because `~/.nrmrc` cache the custom registry.

You can use `nrm del test`, then `vi ~/.nrmrc` and clear your custom registry settings. That's OK.

**Comment by rootical** [comment]
@GoldyMark thanks for suggestion, so why do I need to `nrm del test` then?

**Comment by GoldyMark** [comment]
@rootical Ah ha. You are right. I mistakenly thought about that nrm would write the custom registry into `/usr/local/lib/node_modules/nrm/registries.json`.

**Comment by GoldyMark** [comment]
I found the problem in line 45.
`.command('del|rm <registry>')`

Bug fix:
`.command('del <registry>')`

**Comment by Pines-Cheng** [comment]
这个问题fix了吗？每次都手动清好麻烦。

**Comment by Pana** [comment]
It is fixed now, sorry for the slow response, my apologies

**Comment by AlexJake** [comment]
依然存在这个问题，在ubuntu16下面。如图
![23](https://cloud.githubusercontent.com/assets/3668637/24382607/d6ab410c-1389-11e7-89ad-ebff6155401c.png)

**Comment by GoldyMark** [comment]
@AlexJake 这个命令只适用于自定义的npm仓库，taobao属于nrm内建仓库，不能删除。你可以看一下nrm包下的cli.js的源码（onDel方法）。

**Comment by AlexJake** [comment]
@GoldyMark  删除无所谓的。主要是test Fetch Error的问题。无法测试速度。没看见有具体异常
