### ISSUE TITLE
run command：nrm ls, then error occurrenced

### ISSUE THREAD

**Issue by geedys** [Pana/nrm#174]
(node:19453) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

当我运行命令时报以上错误。
我的环境：
Nodejs version：v22.2.0
NPM verson: 10.7.0

**Comment by a15218378694** [comment]
> (node:19453) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> 当我运行命令时报以上错误。 我的环境： Nodejs version：v22.2.0 NPM verson: 10.7.0

请问解决了吗？我也碰到同样问题
