### ISSUE TITLE
[Style] How to format code

### ISSUE THREAD

**Issue by chouchouji** [Pana/nrm#189]
# Question

I found that I can't format code when I am working for #188. I try to format code(my default formatter is `prettier`), one of the results is that single quotes are turned into double quotes. So, I want to know the way of formating code.  Thanks !

# Link

https://github.com/user-attachments/assets/76440088-54e6-4cdb-9ddb-77d91edeab07

**Comment by iosh** [comment]
I thinks this project is lack configuration for code format, I suggest that #188 only format the modified code, and then we can ad a format configuration for the project ,and format all code.

**Comment by chouchouji** [comment]
> I thinks this project is lack configuration for code format, I suggest that #188 only format the modified code, and then we can ad a format configuration for the project ,and format all code.

Thanks for your reply. I only format the modified code like other for that pr. What format configuration do you want to add? Prettier？

**Comment by chouchouji** [comment]
> Prettier is OK, Do you want PR for this ?

Yes,  I will submit a pr today.
