### ISSUE TITLE
[Improvement] optimize node process code

### ISSUE THREAD

**Issue by chouchouji** [Pana/nrm#204]
Should we remove `process.js` file?  We can replace it with 

```ts
const process = require('node:process')
```

![image](https://github.com/user-attachments/assets/49abcab4-3fca-448a-8d6b-5edba542303b)

![image](https://github.com/user-attachments/assets/b027340f-b2ea-48e0-8b17-655e66e36887)

**Comment by iosh** [comment]
Yes, I think we can safety remove the process.js.
