### ISSUE TITLE
[Feature] Support deleting multiple custom registries

### ISSUE THREAD

**Issue by chouchouji** [Pana/nrm#215]
# Question 

I have three useless custom registry. I want to delete all of them. But I have to delete one by one.  I think it is helpful to support deleting multiple registries. 

![image](https://github.com/user-attachments/assets/49bd8243-d721-440a-867c-17f5a63ed3da)

# Solution

![image](https://github.com/user-attachments/assets/54cbfd7f-5f1f-4796-aa1d-e80aa1b73a32)

[https://github.com/SBoudrias/Inquirer.js/tree/main/packages/checkbox](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/checkbox)

**Comment by iosh** [comment]
Looks good.

**Comment by chouchouji** [comment]
> Looks good.

I think I can submit a pr after v2.0.0. So Will we release today?
