### ISSUE TITLE
bintray support

### ISSUE THREAD

**Issue by criscodex** [Pana/nrm#31]
This is more of a request rather than an issue. Would you be able to add support for `bintray` npm repos/packages?

https://bintray.com

**Comment by Pana** [comment]
What's relation with  Artifactory and Bintray ?

**Comment by criscodex** [comment]
I'm requesting support for Bintray npm registries in `nrm`

**Comment by EmilyMew** [comment]
> I'm requesting support for Bintray npm registries in nrm

@criscodex 
You can simply add a bintray registriy like this:
`$ nrm add <STR_REGISTRY_NAME> https://api.bintray.com/npm/<YOUR_USER_NAME>/<YOUR_REPOSITORY>`
To login with your bintray account, use this command:
`$ nrm set-auth <STR_REGISTRY_NAME> <STR_YOUR_AUTH_BASE_64> <BOOL_IS_ALWAYS_AUTH>`
or later at the next version you can use:
`$ nrm set-auth <STR_REGISTRY_NAME> -a -u <STR_YOUR_USER_NAME> -p <STR_YOUR_API_KEY>`
For setting email use the `nrm set-email <STR_REGISTRY_NAME> <STR_YOUR_EMAIL>` command.

Could that be helpful?
