### ISSUE TITLE
-bash: nrm: command not found

### ISSUE THREAD

**Issue by gy134340** [Pana/nrm#32]
The node version is v7.2.0
The npm version is  5.0.3
The system is macOS

After `npm install -g nrm`, the `nrm ls` do not work as it should. the common line only show 
`-bash: nrm: command not found `.

so confused..

**Comment by Pana** [comment]
It seems like you did not install nrm correctly, you can try to solve it from this direction

**Comment by strongzs** [comment]
![image](https://user-images.githubusercontent.com/10735863/37566030-6b554a06-2aee-11e8-8b87-19dbad95065d.png)

使用npm install -g nrm 安装后就无法使用nrm，不知道是什么原因？我电脑是win10的

**Comment by fengyuanchen** [comment]
对于Windows系统，两种解决方法：
1. 重新安装Node.js。
2. 将`C:\Users\用户名\AppData\Roaming\npm`添加到用户环境变量（因为之前的变量可能被杀毒软件删掉了）。

**Comment by gy134340** [comment]
thanks, guys
