### ISSUE TITLE
如何添加 @scope:<registry>？

### ISSUE THREAD

**Issue by fritx** [Pana/nrm#37]
```plain
# ~/.npmrc
@dxx:registry=https://cnpm.xxx.com:8888
registry=https://registry.npm.taobao.org/
```

**Comment by baixiaoji** [comment]
try
```bash
nrm add @dxx https://cnpm.xxx.com:8888
```

**Comment by fritx** [comment]
@baixiaoji 好像还是做不到，添加后，use @dxx，只能做到

```plain
registry=https://cnpm.xxx.com:8888/
```

而我希望的是只有@dxx的scope走这个，其他的走默认

**Comment by baixiaoji** [comment]
> @baixiaoji 好像还是做不到，添加后，use @dxx，只能做到
> 
> ```
> registry=https://cnpm.xxx.com:8888/
> ```
> 
> 而我希望的是只有@dxx的scope走这个，其他的走默认

这个可能你需要自己去写后续分流的处理逻辑了，nrm的目的只是帮你管理registry的作用。但是我理解中你是自己搭建了一个cnpm。你使用nrm设置里全局的register为你的@scope 的cnpm地址，如有有@scope就找到了，但是没有的话cnpm会有[溯源机制](https://cnpmjs.org/?spm=a2c6h.14275010.0.0.1f9d7a5bvktFmV)，去找到npm的那里的。而这一块你需要查查cnpm文档有没有对应的设置。
![image](https://user-images.githubusercontent.com/21168366/84852441-72241280-b08f-11ea-8a48-4b07d2bc640d.png)
