### ISSUE TITLE
Can nrm hold  difference  setting between global and local 

### ISSUE THREAD

**Issue by july-12** [Pana/nrm#48]
when I type: "nrm use cnpm", all the project will switch to this registry. 
I just want to set local project switch that, don't effect other project's registry,
that mean you could seperate global and local setting.
could you provide extract command to do that, like:
nrm use cnpm -global
nrm use xxx -local

**Comment by iosh** [comment]
Hi @chouchouji  I think this is good feature, Is it possible to simpley create an .npmrc file for the user and write  registry=xxx to resolve this？
What do you think?

**Comment by chouchouji** [comment]
> Hi @chouchouji I think this is good feature, Is it possible to simpley create an .npmrc file for the user and write registry=xxx to resolve this？ What do you think?

I agree with you. I think we should talk about the detail of this feature. It is only for `nrm current` command ? I want to know whether it affect the other commands like `nrm current` or `nrm ls`.

**Comment by iosh** [comment]
> > Hi @chouchouji I think this is good feature, Is it possible to simpley create an .npmrc file for the user and write registry=xxx to resolve this？ What do you think?
> 
> I agree with you. I think we should talk about the detail of this feature. It is only for `nrm use` command ? I want to know whether it affect the other commands like `nrm current` or `nrm ls`.

I think we can first implement the `nrm use` ,and then implement other commands in other PRs.

**Comment by chouchouji** [comment]
> > > Hi @chouchouji I think this is good feature, Is it possible to simpley create an .npmrc file for the user and write registry=xxx to resolve this？ What do you think?
> > 
> > 
> > I agree with you. I think we should talk about the detail of this feature. It is only for `nrm use` command ? I want to know whether it affect the other commands like `nrm current` or `nrm ls`.
> 
> I think we can first implement the `nrm use` ,and then implement other commands in other PRs.

Ok, I will submit a pr in recent days. Thanks for your reply. Good day.
