### ISSUE TITLE
[bug] 当源的 url 中含大写时，nrm current 返回空

### ISSUE THREAD

**Issue by lemon-clown** [Pana/nrm#50]
hey, 问题复现如下：

```shell
nrm add X http://X
nrm current   # 返回空值
nrm ls        # 在 X 项前面没有 * 号标识
npm config get registry # 返回 http://x
```

当把 `X` 替换为 `x` 则没有这个问题，初步判断应该是和 `npm config get registry` 返回的值比对时没有进行大小写转换?

**Comment by jingsam** [comment]
域名不区分大小写

**Comment by lemon-clown** [comment]
额，我知道域名不区分大小写，所以能正常下载包，我的问题是 `nrm current` 会返回空，而产生这个问题的原因我推测是域名大小写的问题，麻烦你看清楚我上面说的，谢谢。

**Comment by EmilyMew** [comment]
感谢反馈。已修复，请等待下次发布。
