### ISSUE TITLE
安装成功后，无法使用

### ISSUE THREAD

**Issue by YiXingYuFeng** [Pana/nrm#62]
执行：npm install -g nrm后显示安装成功
```
  npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/lib/node_modules/node/bin/nrm -> /usr/local/lib/node_modules/node/lib/node_modules/nrm/cli.js
+ nrm@1.2.1
updated 1 package in 6.868s
```
但是执行nrm -v命令时提示nrm不存在

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
show your all config: `npm config list -l`
find the prefix like: 
![npm config prefix](https://user-images.githubusercontent.com/54145886/96206504-9e975f00-0f9b-11eb-90e3-4285bdca9baf.png)

makesure the prefix value in your environment path
