### ISSUE TITLE
nrm 指定源后，yarn 执行读取的还是yarn registry 配置

### ISSUE THREAD

**Issue by grguang** [Pana/nrm#65]
nrm 设置源后，用yarn运行命令，读到的配置还是yarn registry  配置的信息，不知道是否是bug。

**Comment by sunxyw** [comment]
NRM 目前似乎只能更改 NPM 的源，对 Yarn 不起作用。

**Comment by toFrankie** [comment]
请问有没其他工具，可以同步修改 npm、yarn 镜像源？

**Comment by JeffesJiang** [comment]
y

> 请问有没其他工具，可以同步修改 npm、yarn 镜像源？

yrm

**Comment by JeffesJiang** [comment]
> NRM 目前似乎只能更改 NPM 的源，对 Yarn 不起作用。

yrm

**Comment by GuoJikun** [comment]
yarn可以这样设置
```bash
#更改yarn
yarn config set registry https://registry.npm.taobao.org
#更改sass
yarn config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g
```

**Comment by GuoJikun** [comment]
> > NRM 目前似乎只能更改 NPM 的源，对 Yarn 不起作用。
> 
> yrm

竟然还真有yrm😮

**Comment by JeffesJiang** [comment]
> > > NRM 目前似乎只能更改 NPM 的源，对 Yarn 不起作用。
> > 
> > 
> > yrm
> 
> 竟然还真有yrm😮

yrm是nrm 的yarn fork 分支
