### ISSUE TITLE
使用私有的npm仓库，当我使用nrm use xxx时，报错  customRegistries.hasOwnProperty is not a function， v1.2.1

### ISSUE THREAD

**Issue by Lawrence51** [Pana/nrm#74]

**Comment by hanguihe** [comment]
mark

**Comment by bramblex** [comment]
https://github.com/npm/ini/blob/master/ini.js#L86

不关 nrm 的事情，是依赖 ini.js 作的妖……

**Comment by daifuying** [comment]
> https://github.com/npm/ini/blob/master/ini.js#L86
> 
> 不关 nrm 的事情，是依赖 ini.js 作的妖……

怎么解决呀亲？

**Comment by bramblex** [comment]
> > https://github.com/npm/ini/blob/master/ini.js#L86
> > 不关 nrm 的事情，是依赖 ini.js 作的妖……
> 
> 怎么解决呀亲？

可以先手动修改代码简单粗暴解决一下。
node_modules/nrm/cli.js 415行替换成下面代码即可。

```JavaScript
    return fs.existsSync(NRMRC) ? JSON.parse(JSON.stringify(ini.parse(fs.readFileSync(NRMRC, 'utf-8')))) : {};
```

**Comment by marklbp** [comment]
这个问题其实多少和nrm源码严谨度有关系，判断一个属性是否为对象的自有属性，不应该直接在对象上调用一般默认继承的hasOwnProperty方法。

错误示范：
```js
var allRegistries = getAllRegistry();
if (allRegistries.hasOwnProperty(name)) {
     // ...
}
```
正确示范：
```js
var allRegistries = getAllRegistry();
if (Object.prototype.hasOwnProperty.call(allRegistries, name)) {
     // ...
}
```

**Comment by EmilyMew** [comment]
@marklbp 感谢，已经修改了这个问题
