### ISSUE TITLE
使用nrm切换到私有源，在npm install之后如果私有源没有的包会直接报错500

### ISSUE THREAD

**Issue by chuans** [Pana/nrm#78]
使用nrm切换到私有源，在npm install之后如果私有源没有的包会直接报错500
有没有什么方法能够让它在install途中如果私有源里面没有包自动去其他源上下载？比如说taobao
![image](https://user-images.githubusercontent.com/19320399/103351417-204c5280-4ade-11eb-8288-773263e9c5f8.png)

**Comment by wing1003** [comment]
@chuans 可以尝试用我写的小工具 [easy-nrm](https://github.com/wing1003/easy-nrm)

**Comment by chuans** [comment]
> @chuans 可以尝试用我写的小工具 [easy-nrm](https://github.com/wing1003/easy-nrm)

ok 我我试试 实在感谢

**Comment by EmilyMew** [comment]
这个工作一般建议在私有源配置仓库的时候去做，比如在nexus中创建类型为group的仓库，然后将需要的仓库创建为proxy类型之后和自己的私有hosted仓库一并包含在内
