### ISSUE TITLE
 command not found: nrm

### ISSUE THREAD

**Issue by HomyeeKing** [Pana/nrm#88]
after global installed , zsh can't find command

**Comment by wewang-sh** [comment]
same problem, did you resolve this?

**Comment by HomyeeKing** [comment]
@wewang-sh  you can follow the below:

```sh
# check the npm global bin location
npm -g bin  
#or 
which npm


# then check  wether the PATH  has the npm global path or not
echo $PATH

```

if you not find the `npm global` path in the PATH or the path is not right, you can prepend it or just modify the npm global path with the `npm cofig set prefix <the target path>`  command

**Comment by wewang-sh** [comment]
my problem  caused by resolving `npm i -g` need `sudo` on macos with wrong way  ,  and i fixed it by stepping **https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally**
@HomyeeKing  thanks bro
