### ISSUE TITLE
在某些版本的node中使用nrm报错 ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by kKevin0001** [Pana/nrm#93]
node版本：v14.16.1
在我的64位操作系统中运行node时，process.platform会返回“win32”，这实际上应该是node的BUG，但nrm应该也对这种问题作兼容

在nrm/cli.js的第17行使用了process.env.HOME这个环境变量，但这个版本的node没有这个变量，需要将其改成process.env.USERPROFILE

同时为了兼容其它电脑，应该将第17行改成
const NRMRC = path.join(process.env[process.platform == 'win32' ? 'USERPROFILE' : 'HOME'], '.nrmrc');

**Comment by Uaivg** [comment]
刚才查看GitHub上面的nrm代码已经修复了这个BUG，但是npm上面的nrm没有同步这个修改

**Comment by marisarbq** [comment]
+1 同样的问题

**Comment by lanten** [comment]
1.2.2 还是上个月提交的，是联系不上npm所有者了吗？现在 windows 的新版本 node 中无法正常运行，有什么替代方案吗？

**Comment by Uaivg** [comment]
> 1.2.2 还是上个月提交的，是联系不上npm所有者了吗？现在 windows 的新版本 node 中无法正常运行，有什么替代方案吗？

自己改一下nrm的代码就行了，看我上面发的修改方法

**Comment by bokuns** [comment]
> 1.2.2 还是上个月提交的，是联系不上npm所有者了吗？现在 windows 的新版本 node 中无法正常运行，有什么替代方案吗？

可以试一下yrm，感觉和nrm差不多。

**Comment by bhuh12** [comment]
暂时可以使用 github 方式安装

```bash
npm install -g Pana/nrm
```
