### ISSUE TITLE
作者麻烦可以往 npm 上发布一下 1.2.2 吗

### ISSUE THREAD

**Issue by Drincann** [Pana/nrm#95]
0w0

**Comment by LucasIcarus** [comment]
+1

**Comment by Frezc** [comment]
I published a package nrm2 with nrm@1.2.2 code

**Comment by Pana** [comment]
OK

**Comment by bhuh12** [comment]
暂时可以使用 github 方式安装

```bash
npm install -g Pana/nrm
```

**Comment by dyegral** [comment]
npm install -g Pana/nrm 这种安装是什么原理，npm上并没有 Pana/nrm

**Comment by bhuh12** [comment]
> npm install -g Pana/nrm 这种安装是什么原理，npm上并没有 Pana/nrm

使用 GitHub 仓库安装

**Comment by huangshuwei** [comment]
@Pana

**Comment by lizy0329** [comment]
> I published a package nrm2 with nrm@1.2.2 code

mac m1 安装后无法找到命令行，转到 nrm 可以

**Comment by i5ting** [comment]
已经发布了
